project/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static
from video.views import server_static
from project.settings import DEBUG

urlpatterns = [
    path('', include('video.urls', namespace='video')),
    # path('static/<path:resource>', server_static, name='css')
    # path('admin/', admin.site.urls),
]

video/urls.py
from django.urls import path
from django.shortcuts import redirect


from .views import VideoUpload, VideoSearch, About, video_aws_url

app_name = 'video'

urlpatterns = [

        path('', VideoUpload.as_view(), name='upload'),
        path('search/', VideoSearch.as_view(), name='search'),
        path('about/', About.as_view(), name='about'),
        path('download/<str:video_id>', video_aws_url, name='download'),

     
]

video/views.py
import re
import markdown

from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.core.exceptions import BadRequest
from django.shortcuts import render, redirect
from django.core.files.storage import default_storage


from project.settings import BINARY_LOC, README_PATH,  temporary_storage
from project.aws_conf import AWS_MEDIA_DIR, AWS_STATIC_DIR, aws_downloader
from .tasks import Video, video_task
from query import Db_Handler


class VideoUpload(TemplateView):
    template_name = 'video/upload.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        if kwargs.get('uploaded') != None:
            context['uploaded'] = kwargs.get('uploaded')

        return context

    def post(self, request, *args, **kwargs):

        for fileobject in request.FILES.getlist('files'):
            filename = temporary_storage.save(fileobject.name, fileobject)
            video_task.delay(filename, fileobject.name, BINARY_LOC)

        kwargs['uploaded'] = 'Video(s) uploaded'

        return self.get(request,  *args, **kwargs)


class VideoSearch(TemplateView):
    template_name = 'video/search.html'

    def post(self, request, *args, **kwargs):
        string = request.POST.get('sentence').lower()
        word_iter = Video.gen_word_iter(string)

        words = sorted(word_iter, key=lambda word: len(word), reverse=True)

        # list ( generator of list of entries  )
        word_data = list(Db_Handler().query_words(words))

        for entry_list in word_data:  # clean data for display
            if entry_list == []:
                entry_list += [{'video_name': "No record found",
                                'video_id': 'does_not_exist', 'ranges': ''}]
            else:
                for entry in entry_list:
                    try:
                        entry['video_name'] = entry['video_id'].split('_|_')[
                            1]  # remove uuid
                        del entry['word']
                    except Exception as e:
                        print('Hot-gates here', e)

        word_data = dict(zip(words, word_data))
        context = {'data': word_data}
        return render(request, 'video/videolist.html', context)


class About(TemplateView):
    template_name = 'video/about.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        with open(README_PATH, 'r') as file:
            about = file.read()
            about_html = markdown.markdown(about)
        context['about'] = about_html
        return context


def video_aws_url(request, video_id: str, *args, **kwargs):
    """
    Redirects to bucket/media files present on AWS-S3.
    """
    video_url = aws_downloader(AWS_MEDIA_DIR, video_id)
    if video_url is not None:
        return redirect(video_url, *args, permanent=False)
    else:
        raise BadRequest('error')


def server_static(request, resource: str, *args, **kwargs):
    """Redirects to bucket/static files present on AWS-S3."""
    static_url = aws_downloader(AWS_STATIC_DIR, resource)
    if static_url is not None:
        return redirect(static_url, *args, permanent=False)
    else:
        raise BadRequest('error')

templates/base/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">


  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  {% load static %}
  <link rel="stylesheet" href="{% static 'video/style.css' %}" />

</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'video:upload' %}">VIDEO-sub</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'video:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="http://github.com/mayavy" target="_blank">Contact</a>
          </li>

        </ul>

      </div>
    </div>
  </nav>




  {% block content %}

  {% endblock %}


</body>

</html>

templates/video/about.html
{% extends "../base/base.html" %} 
{% block title %}profile{% endblock %} 
{% block content %} 
{% load static %}

</div>

<div class="col p-3 px-5 "  style="background: rgb(114, 249, 240);">
    {{about | safe }}
</div>



{% endblock %}

templates/video/search.html
{% extends "../base/base.html" %}
{% block title %}profile{% endblock %}
{% block content %}
{% load static %}

</div>

<div class="col p-3 px-5 " style="background: rgb(114, 249, 240);">
    <form id="qform" method="post" action="{% url 'video:search' %}">
        {% csrf_token %}
        <h5><label for="query">Search words or phrases in videos </label></h5>
        <textarea id="query" class="col-lg-12" row="5" type="text" name="sentence" required
            placeholder="multiple phrases or words are allowed"></textarea>
        <button type="submit" class="btn btn-success" formtarget="_blank">Search</button>
    </form>
</div>



{% endblock %}

templates/video/upload.html
{% extends "../base/base.html" %}
{% block title %}profile{% endblock %}
{% block content %}



<div id="upload-form" class="container mt-5  ">

    <div class="row  gy-5 ">

        <div class="col-md-6 p-3 px-5" style="background:rgb(25, 204, 240);">
            <form id="imgform" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <h5><label for="up-window">You can upload multiple videos</label></h5>
                <input id="up-window" type="file" multiple name="files" onclick="hide()"
                    accept="video/mp4,video/x-m4v,video/*" required />
                <button type="submit" class="btn btn-dark" onclick="loading()">Upload</button>
            </form>
        </div>

        <div class="col-md-6 p-3 px-5 " style="background: rgb(114, 249, 240);">
            <form id="qform" method="post" action="{% url 'video:search' %}">
                {% csrf_token %}
                <h5><label for="query">Search words or phrases in videos </label></h5>
                <textarea id="query" class="col-lg-12" row="5" type="text" name="sentence" required
                    placeholder="multiple phrases or words are allowed"></textarea>
                <button type="submit" class="btn btn-success" formtarget="_blank">Search</button>
            </form>
        </div>

    </div>
</div>

<div class="container">
    <div id="progress" class="col mt-5 progress" style="height: 10px;" hidden>
        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75"
            aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
    </div>

    <div id="alert-card" class="col mt-2 border border-warning text-center rounded-pill  ">
        <div id="loading" hidden style="color: green; font-weight: bold;">Uploading.., time depends on your internet
            connection and upload
            size.</div>
        <div id="uploaded">{{uploaded}}</div>
        <div id="inform" hidden style="color: green; font-weight: bold;">Depending upon number of files and size,
            processing migth take few seconds or couple minutes to show
            uploads in search result.
        </div>
    </div>

    <script>
        if (document.getElementById("uploaded").textContent != "") {
            alert("{{uploaded}}")
            setTimeout(() => { document.getElementById("uploaded").setAttribute("hidden", true) }, 7000)
            setTimeout(() => { document.getElementById("inform").removeAttribute("hidden") }, 7000)
            setTimeout(() => { document.getElementById("inform").setAttribute("hidden", true) }, 23000)
        };

    </script>
</div>

<script>

    function hide() {
        setTimeout(() => { document.getElementById("progress").setAttribute("hidden", true) }, 0)
        setTimeout(() => { document.getElementById("loading").setAttribute("hidden", true) }, 0)

    }

    function loading() {

        if (document.getElementById("up-window").value != "") {
            setTimeout(() => { document.getElementById("progress").removeAttribute("hidden") }, 0)
            setTimeout(() => { document.getElementById("loading").removeAttribute("hidden") }, 0)
            setTimeout(() => { document.getElementById("loading").setAttribute("hidden", true) }, 15000)
        };
    }
</script>

{% endblock %}

templates/video/videolist.html
{% extends "../base/base.html" %}
{% block title %}profile{% endblock %}
{% block content %}

<h3 class="px-md-5 mt-2 ">Time segments within each video where search word or phrases matched</h3>
<div class="duration border container fs-6 ">
  <!-- <div class="row"> -->
  <div id="start" class="col ">Start(hh:mm:ss,milliseconds)</div>
  <div id="end" class="col">End(hh:mm:ss,milliseconds)</div>
</div>
<!-- </div> -->
{% for word,list in data.items %}


<div id="word-card" class="card-body container border border-info mt-2">
  <h3 class=" text-start fs-4">{{word}}</h3>
  {% for entry in list %}
  {% if forloop.counter <= 2 %} <div id="video-card"
    class="fs-4  shadow border rounded-2 border-primary mb-1 container">
    <span><a class="fst-italic" href="{% url 'video:download' video_id=entry.video_id %}">
        {{entry.video_name}}</a>
      <time class="fw-light fs-6">Uploaded by {{entry.uploaded_by}}</time>
    </span> <br />
    <div class="row text-center ">

      {% for timestep in entry.ranges %}
      <div class="duration border  m-1 col  fs-6">
        <div id="start" class="col">{{ timestep.0 }}</div>
        <div id="end" class="col">{{ timestep.1 }}</div>
      </div>
      {% endfor %}

    </div><br />
</div>

{% endif %}
{% endfor %}

{% if not list|length <= 2 %} <button id="expand-videos" class="container btn btn-primary mt-0 mb-1" type="button"
  data-bs-toggle="collapse" data-bs-target="#collapse-{{ word }}" aria-expanded="false"
  aria-controls="collapse-{{ word }}">
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-down-fill"
    viewBox="0 0 16 16">
    <path
      d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z" />
  </svg>
  </button>
  {% endif %}

  <div class="collapse" id="collapse-{{ word }}">
    {% for entry in list %}

    {% if forloop.counter > 2 %}




    <div id="video-card" class="fs-4  shadow border rounded-2 border-primary mb-1 container">
      <span><a class="fst-italic" href="{% url 'video:download' video_id=entry.video_id %}">
          {{entry.video_name}}</a>
        <time class="fw-light fs-6">Uploaded by {{entry.uploaded_by}}</time>
      </span> <br />
      <div class="row text-center ">

        {% for timestep in entry.ranges %}
        <div class="duration border  m-1 col  fs-6">
          <div id="start" class="col">{{ timestep.0 }}</div>
          <div id="end" class="col">{{ timestep.1 }}</div>
        </div>
        {% endfor %}

      </div><br />
    </div>

    {% endif %}
    {% endfor %}

  </div>







  </div>
  {% endfor %}

  {% endblock %}